name: 'Deploy to AWS S3'
description: 'Deploy a static wesbsite'
inputs:
   BUCKET:
      description: 'The S3 bucket name'
      required: true
   BUCKET-REGION:
      description: 'The region of bucket'
      required: 'false'
      default: 'us-east-1'
   DIST-FOLDER:
      description: 'The folder containing the deployable files'
      required: 'true'
outputs:
   website-url:
      description: 'The URL of website'
runs:
   using: 'docker'
   image: 'Dockerfile'